# Generated by Django 4.2.4 on 2023-08-08 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='islamiccalender',
            name='day',
        ),
        migrations.RemoveField(
            model_name='islamiccalender',
            name='month',
        ),
        migrations.RemoveField(
            model_name='islamiccalender',
            name='year',
        ),
        migrations.AddField(
            model_name='islamiccalender',
            name='gregorian_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
